name: tool
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  args: ^2.4.2
  charcode: ^1.1.3
  glob: ^2.1.2
  image: ^4.0.17
  markdown: ^7.1.1
  mime_type: ^1.0.0
  mustache_template: ^2.0.0
  path: ^1.7.0
  pool: ^1.4.0
  sass: ^1.26.5
  shelf: ^1.4.1
  string_scanner: ^1.0.5
