# This workflow will build the rust interpreter of lox

name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Install cargo-hack
      run: cargo install cargo-hack --locked
    - name: Build
      run: |
        cargo hack build --feature-powerset --skip print_code_builtin,trace_execution_builtin,debug_parser_builtin,debug_scanner_builtin --no-dev-deps
        cargo build --verbose
    - name: Lint
      run: |
        rustup component add clippy
        # Run normal configuration and fail on default warnings
        cargo clippy -- -D warnings
        # Run pedantic
        cargo clippy --all-targets -- -W clippy::all -W clippy::pedantic -W clippy::nursery -W clippy::cargo
        cargo hack clippy --each-feature --no-dev-deps -- -W clippy::all -W clippy::pedantic -W clippy::nursery -W clippy::cargo
    - name: Test
      run: cargo test --verbose
    - name: Install Miri
      run: |
        rustup toolchain install nightly --component miri
        cargo +nightly miri setup
    - name: Test with MIRI
      run: |
        cargo +nightly miri test --verbose
    - name: Run an example with MIRI
      run: |
        MIRIFLAGS=-Zmiri-disable-isolation cargo +nightly miri run -- test/overloading/overloading_for_in.gen
    - name: Check print_code
      run: |
        cargo run --features "print_code" test/number/equality.gen
    - name: Check trace_execution_verbose
      run: |
        cargo run --features "trace_execution_verbose" test/number/equality.gen
    - name: Check debug_parser
      run: |
        ! cargo run --features "debug_parser" test/function_literals/neither_block_nor_expression.gen
    - name: Check debug_scanner
      run: |
        cargo run --features "debug_scanner" test/fstrings/nested.gen
    - name: Setup dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
    - name: Checkout book repo
      uses: actions/checkout@v4
      with:
        repository: munificent/craftinginterpreters
        path: reference/craftinginterpreters
    - name: Setup book repo
      working-directory: reference/craftinginterpreters
      run: |
        make clox
        make jlox
    - name: Run custom dart tests
      run: |
        cargo build
        make test
    - name: Install hyperfine
      run: |
        cargo install --locked hyperfine
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.4.2"
    - name: Run benchmarks
      run: make benchmark-ci
